<project xmlns="http://maven.apache.org/POM/4.0.0"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/maven-v4_0_0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <artifactId>video4j-facedetect</artifactId>
    <packaging>pom</packaging>

    <parent>
        <groupId>io.metaloom.video</groupId>
        <artifactId>video4j-parent</artifactId>
        <version>2.0.0-SNAPSHOT</version>
    </parent>

    <name>video4j-facedetect</name>
    <description>Video4j extension which provides video face detection</description>
    <inceptionYear>2023</inceptionYear>

    <properties>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
        <video4j.version>2.0.0-SNAPSHOT</video4j.version>
    </properties>

    <modules>
        <module>common</module>
        <module>dlib</module>
        <module>opencv</module>
        <module>inspireface</module>
        <module>insightface-http</module>
    </modules>

    <dependencies>
        <dependency>
            <groupId>org.slf4j</groupId>
            <artifactId>slf4j-api</artifactId>
        </dependency>

        <!-- Test -->
        <dependency>
            <groupId>org.junit.jupiter</groupId>
            <artifactId>junit-jupiter</artifactId>
            <scope>test</scope>
        </dependency>
    </dependencies>

    <build>
        <plugins>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-compiler-plugin</artifactId>
                <configuration>
                    <release>25</release>
                </configuration>
            </plugin>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-resources-plugin</artifactId>
                <version>3.3.1</version>
                <inherited>false</inherited>
                <executions>
                    <execution>
                        <id>readme-md</id>
                        <phase>clean</phase>
                        <goals>
                            <goal>copy-resources</goal>
                        </goals>
                        <configuration>
                            <outputDirectory>${project.basedir}</outputDirectory>
                            <resources>
                                <resource>
                                    <directory>${project.basedir}/.github/md</directory>
                                    <includes>
                                        <include>README.md</include>
                                    </includes>
                                    <filtering>true</filtering>
                                </resource>
                            </resources>
                            <encoding>UTF-8</encoding>
                            <mavenFilteringHints>
                                <mavenFilteringHint>snippetFilter</mavenFilteringHint>
                            </mavenFilteringHints>
                        </configuration>
                    </execution>
                </executions>
                <dependencies>
                    <dependency>
                        <groupId>io.metaloom.maven</groupId>
                        <artifactId>snippet-resource-filter</artifactId>
                        <version>0.1.1</version>
                    </dependency>
                </dependencies>
            </plugin>
        </plugins>
    </build>
</project>